### ISSUE TITLE
Show outline between meshes of same color?

### ISSUE THREAD

**Issue by isorokuYam** [cakeslice/Outline-Effect#63] opened 2023-05-31 13:50 UTC
Hello.
Is it possible to show borders of same color between meshes?
I have a map created from meshes (created from PolygonCollider2D) - all with same fill color. 
If i set different outline colors between parts of the map - it's ok. If I move one element on distance from others - is ok (blue on example). But I have no idea how to outline all parts with same color e.g color1. Looks like all meshes with same outline color are merged into one, big one.
Light green colider on the middle is example without outline.
![image](https://github.com/cakeslice/Outline-Effect/assets/52502292/febc89f1-ca92-4b95-8630-7b8baf9c1ac4)

It's possible that is just how it works and it's just not the tool for my scenario :<

**Comment by cakeslice** [comment] 2023-12-05 23:20
Duplicate of https://github.com/cakeslice/Outline-Effect/issues/31

**Closed as not planned by cakeslice** 2023-12-05 23:20 UTC
